export enum pokemonTypeColors {
        fire = '#EE8130',
        grass = '#7AC74C',
        electric = 'rgb(255 242 113)',
        rock = '#B6A136',
        fairy = '#D68F7D02C',
        water = '#6390F0',
        ground = '#E5AD',
        poison = '#A33EA1',
        bug = '#A6B91A',
        dragon = '#6F35FC',
        psychic = '#F95587',
        flying = '#A98FF3',
        fighting = '#C22E28',
        normal = '#A8A77A',
        ice = '#96D9D6',
        ghost = '#735797',
        dark = '#705746',
        steel = '#B7B7CE',
}
export enum pokemonType {
        fire = 'fire',
        grass = 'grass',
        electric = 'electric',
        rock = 'rock',
        fairy = 'fairy',
        water = 'water',
        ground = 'ground',
        poison = 'poison',
        bug = 'bug',
        dragon = 'dragon',
        psychic = 'psychic',
        flying = 'flying',
        fighting = 'fighting',
        normal = 'normal',
        ice = 'ice',
        ghost = 'ghost',
        dark = 'dark',
        steel = 'steel',
        unknown = 'unknown',
}
