import { useTranslations } from "next-intl";


export enum pokemonTypeColors {
        fire = '#EE8130',
        grass = '#7AC74C',
        electric = 'rgb(255 242 113)',
        rock = '#B6A136',
        fairy = '#D68F7D02C',
        water = '#6390F0',
        ground = '#E5AD',
        poison = '#A33EA1',
        bug = '#A6B91A',
        dragon = '#6F35FC',
        psychic = '#F95587',
        flying = '#A98FF3',
        fighting = '#C22E28',
        normal = '#A8A77A',
        ice = '#96D9D6',
        ghost = '#735797',
        dark = '#705746',
        steel = '#B7B7CE',
}
export enum pokemonType {
        Fuego = 'fire',
        Hierba = 'grass',
        Electricidad = 'electric',
        Piedra = 'rock',
        Hada = 'fairy',
        Agua = 'water',
        Tierra = 'ground',
        Veneno = 'poison',
        Insecto = 'bug',
        Dragon = 'dragon',
        Psiquico = 'psychic',
        Volador = 'flying',
        Pelea = 'fighting',
        Normal = 'normal',
        Hielo = 'ice',
        Fantasma = 'ghost',
        Oscuridad = 'dark',
        Acero = 'steel',
        Cualquiera = 'unknown',
}
